package:
  name: m2-binary-packages
  version: 20230914

source:
  - url:
      - https://repo.msys2.org/msys/x86_64/filesystem-2023.02.07-1-x86_64.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914/filesystem-2023.02.07-1-x86_64.pkg.tar.zst
    sha256: 7ab6ed1bed694b51f6c54df0f315ea8dbbed7fb149af66740df4ef20f2449281
    folder: binary-m2-filesystem
    patches:
      - patches/filesystem/0001-Remove-etc-post-install-07-pacman-key-post.patch
      - patches/filesystem/0002-Use-Windows-users-temporary-directory-as-tmp.patch
      - patches/filesystem/0003-Fix-bin-PATH-issue.patch

  - url:
      - https://repo.msys2.org/msys/sources/filesystem-2023.02.07-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914/filesystem-2023.02.07-1.src.tar.zst
    sha256: 37bf08b7cc8e67acb2a2d15e07284c3c401d770d08b0a6daf83b0ec87b7a3a3c
    folder: source-filesystem

build:
  number: 0
  noarch: generic
  error_overlinking: false

outputs:
  - name: m2-filesystem
    version: 2023.02.07.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - m2-conda-epoch 20230914
      run:
        - m2-conda-epoch 20230914
    about:
      home: https://github.com/msys2/MSYS2-packages/tree/master/filesystem
      license: BSD-3-Clause
      summary: |
        Base filesystem

about:
  home: https://github.com/conda-forge/m2-recipes-feedstock
  summary: Repackaged msys2 x86_64 binaries

extra:
  recipe-maintainers:
    - isuruf
