remote_ci_setup:
- conda-forge-ci-setup=4
- conda-build=3.28.4
noarch_platforms:
- win_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
conda_build_tool: rattler-build
conda_install_tool: pixi
